// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package session

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sessionFieldNames          = builder.RawFieldNames(&Session{})
	sessionRows                = strings.Join(sessionFieldNames, ",")
	sessionRowsExpectAutoSet   = strings.Join(stringx.Remove(sessionFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sessionRowsWithPlaceHolder = strings.Join(stringx.Remove(sessionFieldNames, "`session_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheSessionSessionIdPrefix = "cache:session:sessionId:"
)

type (
	sessionModel interface {
		Insert(ctx context.Context, data *Session) (sql.Result, error)
		FindOne(ctx context.Context, sessionId int64) (*Session, error)
		Update(ctx context.Context, data *Session) error
		Delete(ctx context.Context, sessionId int64) error
	}

	defaultSessionModel struct {
		sqlc.CachedConn
		table string
	}

	Session struct {
		SessionId   int64     `db:"session_id"`   // 会话 ID
		Name        string    `db:"name"`         // 名称
		Type        int64     `db:"type"`         // 类别：0 单聊，1 群聊，2 机器人
		Status      int64     `db:"status"`       // 状态：0 正常，1 删除
		CreatedTime time.Time `db:"created_time"` // 创建时间
		UpdatedTime time.Time `db:"updated_time"` // 更新时间
		Avatar      string    `db:"avatar"`       // 用户头像
	}
)

func newSessionModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSessionModel {
	return &defaultSessionModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`session`",
	}
}

func (m *defaultSessionModel) Delete(ctx context.Context, sessionId int64) error {
	sessionSessionIdKey := fmt.Sprintf("%s%v", cacheSessionSessionIdPrefix, sessionId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `session_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, sessionId)
	}, sessionSessionIdKey)
	return err
}

func (m *defaultSessionModel) FindOne(ctx context.Context, sessionId int64) (*Session, error) {
	sessionSessionIdKey := fmt.Sprintf("%s%v", cacheSessionSessionIdPrefix, sessionId)
	var resp Session
	err := m.QueryRowCtx(ctx, &resp, sessionSessionIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `session_id` = ? limit 1", sessionRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, sessionId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSessionModel) Insert(ctx context.Context, data *Session) (sql.Result, error) {
	sessionSessionIdKey := fmt.Sprintf("%s%v", cacheSessionSessionIdPrefix, data.SessionId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, sessionRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.SessionId, data.Name, data.Type, data.Status, data.CreatedTime, data.UpdatedTime, data.Avatar)
	}, sessionSessionIdKey)
	return ret, err
}

func (m *defaultSessionModel) Update(ctx context.Context, data *Session) error {
	sessionSessionIdKey := fmt.Sprintf("%s%v", cacheSessionSessionIdPrefix, data.SessionId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `session_id` = ?", m.table, sessionRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.Type, data.Status, data.CreatedTime, data.UpdatedTime, data.Avatar, data.SessionId)
	}, sessionSessionIdKey)
	return err
}

func (m *defaultSessionModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSessionSessionIdPrefix, primary)
}

func (m *defaultSessionModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `session_id` = ? limit 1", sessionRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSessionModel) tableName() string {
	return m.table
}
