// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package message

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	messageFieldNames          = builder.RawFieldNames(&Message{})
	messageRows                = strings.Join(messageFieldNames, ",")
	messageRowsExpectAutoSet   = strings.Join(stringx.Remove(messageFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	messageRowsWithPlaceHolder = strings.Join(stringx.Remove(messageFieldNames, "`message_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMessageMessageIdPrefix = "cache:message:messageId:"
)

type (
	messageModel interface {
		Insert(ctx context.Context, data *Message) (sql.Result, error)
		FindOne(ctx context.Context, messageId int64) (*Message, error)
		Update(ctx context.Context, data *Message) error
		Delete(ctx context.Context, messageId int64) error
	}

	defaultMessageModel struct {
		sqlc.CachedConn
		table string
	}

	Message struct {
		MessageId   int64         `db:"message_id"`   // 消息 id
		SenderId    int64         `db:"sender_id"`    // 发送者 id
		SessionId   int64         `db:"session_id"`   // 会话 id
		Type        int64         `db:"type"`         // 消息类型: 0 文本消息，1 图片消息，2 表情包，3 红包
		Content     string        `db:"content"`      // 消息内容
		ReplyId     sql.NullInt64 `db:"reply_id"`     // 消息引用 id
		SessionType int64         `db:"session_type"` // 会话类型: 0 单聊，1 群聊，2机器人会话
		CreatedTime time.Time     `db:"created_time"` // 创建时间
		UpdatedTime time.Time     `db:"updated_time"` // 更新时间
	}
)

func newMessageModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMessageModel {
	return &defaultMessageModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`message`",
	}
}

func (m *defaultMessageModel) Delete(ctx context.Context, messageId int64) error {
	messageMessageIdKey := fmt.Sprintf("%s%v", cacheMessageMessageIdPrefix, messageId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `message_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, messageId)
	}, messageMessageIdKey)
	return err
}

func (m *defaultMessageModel) FindOne(ctx context.Context, messageId int64) (*Message, error) {
	messageMessageIdKey := fmt.Sprintf("%s%v", cacheMessageMessageIdPrefix, messageId)
	var resp Message
	err := m.QueryRowCtx(ctx, &resp, messageMessageIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `message_id` = ? limit 1", messageRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, messageId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMessageModel) Insert(ctx context.Context, data *Message) (sql.Result, error) {
	messageMessageIdKey := fmt.Sprintf("%s%v", cacheMessageMessageIdPrefix, data.MessageId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, messageRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MessageId, data.SenderId, data.SessionId, data.Type, data.Content, data.ReplyId, data.SessionType, data.CreatedTime, data.UpdatedTime)
	}, messageMessageIdKey)
	return ret, err
}

func (m *defaultMessageModel) Update(ctx context.Context, data *Message) error {
	messageMessageIdKey := fmt.Sprintf("%s%v", cacheMessageMessageIdPrefix, data.MessageId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `message_id` = ?", m.table, messageRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.SenderId, data.SessionId, data.Type, data.Content, data.ReplyId, data.SessionType, data.CreatedTime, data.UpdatedTime, data.MessageId)
	}, messageMessageIdKey)
	return err
}

func (m *defaultMessageModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMessageMessageIdPrefix, primary)
}

func (m *defaultMessageModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `message_id` = ? limit 1", messageRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMessageModel) tableName() string {
	return m.table
}
