// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package friend

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	friendFieldNames          = builder.RawFieldNames(&Friend{})
	friendRows                = strings.Join(friendFieldNames, ",")
	friendRowsExpectAutoSet   = strings.Join(stringx.Remove(friendFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	friendRowsWithPlaceHolder = strings.Join(stringx.Remove(friendFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheFriendIdPrefix             = "cache:friend:id:"
	cacheFriendUserIdFriendIdPrefix = "cache:friend:userId:friendId:"
)

type (
	friendModel interface {
		Insert(ctx context.Context, data *Friend) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Friend, error)
		FindOneByUserIdFriendId(ctx context.Context, userId int64, friendId int64) (*Friend, error)
		Update(ctx context.Context, data *Friend) error
		Delete(ctx context.Context, id int64) error
	}

	defaultFriendModel struct {
		sqlc.CachedConn
		table string
	}

	Friend struct {
		Id          int64     `db:"id"`           // 主键
		UserId      int64     `db:"user_id"`      // 用户 ID
		FriendId    int64     `db:"friend_id"`    // 好友 ID
		Status      int64     `db:"status"`       // 好友状态：0好友，1拉黑，2删除
		CreatedTime time.Time `db:"created_time"` // 创建时间
		UpdatedTime time.Time `db:"updated_time"` // 更新时间
	}
)

func newFriendModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFriendModel {
	return &defaultFriendModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`friend`",
	}
}

func (m *defaultFriendModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	friendIdKey := fmt.Sprintf("%s%v", cacheFriendIdPrefix, id)
	friendUserIdFriendIdKey := fmt.Sprintf("%s%v:%v", cacheFriendUserIdFriendIdPrefix, data.UserId, data.FriendId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, friendIdKey, friendUserIdFriendIdKey)
	return err
}

func (m *defaultFriendModel) FindOne(ctx context.Context, id int64) (*Friend, error) {
	friendIdKey := fmt.Sprintf("%s%v", cacheFriendIdPrefix, id)
	var resp Friend
	err := m.QueryRowCtx(ctx, &resp, friendIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendModel) FindOneByUserIdFriendId(ctx context.Context, userId int64, friendId int64) (*Friend, error) {
	friendUserIdFriendIdKey := fmt.Sprintf("%s%v:%v", cacheFriendUserIdFriendIdPrefix, userId, friendId)
	var resp Friend
	err := m.QueryRowIndexCtx(ctx, &resp, friendUserIdFriendIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `friend_id` = ? limit 1", friendRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, friendId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendModel) Insert(ctx context.Context, data *Friend) (sql.Result, error) {
	friendIdKey := fmt.Sprintf("%s%v", cacheFriendIdPrefix, data.Id)
	friendUserIdFriendIdKey := fmt.Sprintf("%s%v:%v", cacheFriendUserIdFriendIdPrefix, data.UserId, data.FriendId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, friendRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.FriendId, data.Status, data.CreatedTime, data.UpdatedTime)
	}, friendIdKey, friendUserIdFriendIdKey)
	return ret, err
}

func (m *defaultFriendModel) Update(ctx context.Context, newData *Friend) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	friendIdKey := fmt.Sprintf("%s%v", cacheFriendIdPrefix, data.Id)
	friendUserIdFriendIdKey := fmt.Sprintf("%s%v:%v", cacheFriendUserIdFriendIdPrefix, data.UserId, data.FriendId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, friendRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.FriendId, newData.Status, newData.CreatedTime, newData.UpdatedTime, newData.Id)
	}, friendIdKey, friendUserIdFriendIdKey)
	return err
}

func (m *defaultFriendModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheFriendIdPrefix, primary)
}

func (m *defaultFriendModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFriendModel) tableName() string {
	return m.table
}
