// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package user_balance

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userBalanceFieldNames          = builder.RawFieldNames(&UserBalance{})
	userBalanceRows                = strings.Join(userBalanceFieldNames, ",")
	userBalanceRowsExpectAutoSet   = strings.Join(stringx.Remove(userBalanceFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userBalanceRowsWithPlaceHolder = strings.Join(stringx.Remove(userBalanceFieldNames, "`user_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserBalanceUserIdPrefix = "cache:userBalance:userId:"
)

type (
	userBalanceModel interface {
		Insert(ctx context.Context, data *UserBalance) (sql.Result, error)
		FindOne(ctx context.Context, userId int64) (*UserBalance, error)
		Update(ctx context.Context, data *UserBalance) error
		Delete(ctx context.Context, userId int64) error
	}

	defaultUserBalanceModel struct {
		sqlc.CachedConn
		table string
	}

	UserBalance struct {
		UserId      int64     `db:"user_id"`      // 用户 ID
		Balance     int64     `db:"balance"`      // 余额 (单位：分)
		CreatedTime time.Time `db:"created_time"` // 创建时间
		UpdatedTime time.Time `db:"updated_time"` // 更新时间
	}
)

func newUserBalanceModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserBalanceModel {
	return &defaultUserBalanceModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_balance`",
	}
}

func (m *defaultUserBalanceModel) Delete(ctx context.Context, userId int64) error {
	userBalanceUserIdKey := fmt.Sprintf("%s%v", cacheUserBalanceUserIdPrefix, userId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `user_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, userId)
	}, userBalanceUserIdKey)
	return err
}

func (m *defaultUserBalanceModel) FindOne(ctx context.Context, userId int64) (*UserBalance, error) {
	userBalanceUserIdKey := fmt.Sprintf("%s%v", cacheUserBalanceUserIdPrefix, userId)
	var resp UserBalance
	err := m.QueryRowCtx(ctx, &resp, userBalanceUserIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", userBalanceRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, userId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserBalanceModel) Insert(ctx context.Context, data *UserBalance) (sql.Result, error) {
	userBalanceUserIdKey := fmt.Sprintf("%s%v", cacheUserBalanceUserIdPrefix, data.UserId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, userBalanceRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.Balance, data.CreatedTime, data.UpdatedTime)
	}, userBalanceUserIdKey)
	return ret, err
}

func (m *defaultUserBalanceModel) Update(ctx context.Context, data *UserBalance) error {
	userBalanceUserIdKey := fmt.Sprintf("%s%v", cacheUserBalanceUserIdPrefix, data.UserId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `user_id` = ?", m.table, userBalanceRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Balance, data.CreatedTime, data.UpdatedTime, data.UserId)
	}, userBalanceUserIdKey)
	return err
}

func (m *defaultUserBalanceModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserBalanceUserIdPrefix, primary)
}

func (m *defaultUserBalanceModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", userBalanceRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserBalanceModel) tableName() string {
	return m.table
}
