// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package apply_friend

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	applyFriendFieldNames          = builder.RawFieldNames(&ApplyFriend{})
	applyFriendRows                = strings.Join(applyFriendFieldNames, ",")
	applyFriendRowsExpectAutoSet   = strings.Join(stringx.Remove(applyFriendFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	applyFriendRowsWithPlaceHolder = strings.Join(stringx.Remove(applyFriendFieldNames, "`apply_friend_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheApplyFriendApplyFriendIdPrefix      = "cache:applyFriend:applyFriendId:"
	cacheApplyFriendSenderIdReceiverIdPrefix = "cache:applyFriend:senderId:receiverId:"
)

type (
	applyFriendModel interface {
		Insert(ctx context.Context, data *ApplyFriend) (sql.Result, error)
		FindOne(ctx context.Context, applyFriendId int64) (*ApplyFriend, error)
		FindOneBySenderIdReceiverId(ctx context.Context, senderId int64, receiverId int64) (*ApplyFriend, error)
		Update(ctx context.Context, data *ApplyFriend) error
		Delete(ctx context.Context, applyFriendId int64) error
	}

	defaultApplyFriendModel struct {
		sqlc.CachedConn
		table string
	}

	ApplyFriend struct {
		ApplyFriendId int64     `db:"apply_friend_id"` // 申请 ID
		SenderId      int64     `db:"sender_id"`       // 发送者用户 ID
		ReceiverId    int64     `db:"receiver_id"`     // 接收者用户 ID
		Message       string    `db:"message"`         // 申请信息
		Status        int64     `db:"status"`          // 申请状态。0未读，1通过，2拒绝，3已读，4过期
		CreatedTime   time.Time `db:"created_time"`    // 创建时间
		UpdatedTime   time.Time `db:"updated_time"`    // 更新时间
	}
)

func newApplyFriendModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultApplyFriendModel {
	return &defaultApplyFriendModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`apply_friend`",
	}
}

func (m *defaultApplyFriendModel) Delete(ctx context.Context, applyFriendId int64) error {
	data, err := m.FindOne(ctx, applyFriendId)
	if err != nil {
		return err
	}

	applyFriendApplyFriendIdKey := fmt.Sprintf("%s%v", cacheApplyFriendApplyFriendIdPrefix, applyFriendId)
	applyFriendSenderIdReceiverIdKey := fmt.Sprintf("%s%v:%v", cacheApplyFriendSenderIdReceiverIdPrefix, data.SenderId, data.ReceiverId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `apply_friend_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, applyFriendId)
	}, applyFriendApplyFriendIdKey, applyFriendSenderIdReceiverIdKey)
	return err
}

func (m *defaultApplyFriendModel) FindOne(ctx context.Context, applyFriendId int64) (*ApplyFriend, error) {
	applyFriendApplyFriendIdKey := fmt.Sprintf("%s%v", cacheApplyFriendApplyFriendIdPrefix, applyFriendId)
	var resp ApplyFriend
	err := m.QueryRowCtx(ctx, &resp, applyFriendApplyFriendIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `apply_friend_id` = ? limit 1", applyFriendRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, applyFriendId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultApplyFriendModel) FindOneBySenderIdReceiverId(ctx context.Context, senderId int64, receiverId int64) (*ApplyFriend, error) {
	applyFriendSenderIdReceiverIdKey := fmt.Sprintf("%s%v:%v", cacheApplyFriendSenderIdReceiverIdPrefix, senderId, receiverId)
	var resp ApplyFriend
	err := m.QueryRowIndexCtx(ctx, &resp, applyFriendSenderIdReceiverIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `sender_id` = ? and `receiver_id` = ? limit 1", applyFriendRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, senderId, receiverId); err != nil {
			return nil, err
		}
		return resp.ApplyFriendId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultApplyFriendModel) Insert(ctx context.Context, data *ApplyFriend) (sql.Result, error) {
	applyFriendApplyFriendIdKey := fmt.Sprintf("%s%v", cacheApplyFriendApplyFriendIdPrefix, data.ApplyFriendId)
	applyFriendSenderIdReceiverIdKey := fmt.Sprintf("%s%v:%v", cacheApplyFriendSenderIdReceiverIdPrefix, data.SenderId, data.ReceiverId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, applyFriendRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ApplyFriendId, data.SenderId, data.ReceiverId, data.Message, data.Status, data.CreatedTime, data.UpdatedTime)
	}, applyFriendApplyFriendIdKey, applyFriendSenderIdReceiverIdKey)
	return ret, err
}

func (m *defaultApplyFriendModel) Update(ctx context.Context, newData *ApplyFriend) error {
	data, err := m.FindOne(ctx, newData.ApplyFriendId)
	if err != nil {
		return err
	}

	applyFriendApplyFriendIdKey := fmt.Sprintf("%s%v", cacheApplyFriendApplyFriendIdPrefix, data.ApplyFriendId)
	applyFriendSenderIdReceiverIdKey := fmt.Sprintf("%s%v:%v", cacheApplyFriendSenderIdReceiverIdPrefix, data.SenderId, data.ReceiverId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `apply_friend_id` = ?", m.table, applyFriendRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.SenderId, newData.ReceiverId, newData.Message, newData.Status, newData.CreatedTime, newData.UpdatedTime, newData.ApplyFriendId)
	}, applyFriendApplyFriendIdKey, applyFriendSenderIdReceiverIdKey)
	return err
}

func (m *defaultApplyFriendModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheApplyFriendApplyFriendIdPrefix, primary)
}

func (m *defaultApplyFriendModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `apply_friend_id` = ? limit 1", applyFriendRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultApplyFriendModel) tableName() string {
	return m.table
}
