// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package system_notification

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	systemNotificationFieldNames          = builder.RawFieldNames(&SystemNotification{})
	systemNotificationRows                = strings.Join(systemNotificationFieldNames, ",")
	systemNotificationRowsExpectAutoSet   = strings.Join(stringx.Remove(systemNotificationFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	systemNotificationRowsWithPlaceHolder = strings.Join(stringx.Remove(systemNotificationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheSystemNotificationIdPrefix        = "cache:systemNotification:id:"
	cacheSystemNotificationMessageIdPrefix = "cache:systemNotification:messageId:"
)

type (
	systemNotificationModel interface {
		Insert(ctx context.Context, data *SystemNotification) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SystemNotification, error)
		FindOneByMessageId(ctx context.Context, messageId string) (*SystemNotification, error)
		Update(ctx context.Context, data *SystemNotification) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSystemNotificationModel struct {
		sqlc.CachedConn
		table string
	}

	SystemNotification struct {
		Id          int64     `db:"id"`           // 主键ID（雪花ID）
		MessageId   string    `db:"message_id"`   // 消息ID（用于去重）
		ReceiverId  int64     `db:"receiver_id"`  // 接收者用户ID
		Type        int64     `db:"type"`         // 通知类型：101好友申请，102新会话，103群聊邀请
		Content     string    `db:"content"`      // 完整通知内容（JSON格式）
		IsRead      int64     `db:"is_read"`      // 是否已读：0未读，1已读
		CreatedTime time.Time `db:"created_time"` // 创建时间
		UpdatedTime time.Time `db:"updated_time"` // 更新时间
	}
)

func newSystemNotificationModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSystemNotificationModel {
	return &defaultSystemNotificationModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`system_notification`",
	}
}

func (m *defaultSystemNotificationModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	systemNotificationIdKey := fmt.Sprintf("%s%v", cacheSystemNotificationIdPrefix, id)
	systemNotificationMessageIdKey := fmt.Sprintf("%s%v", cacheSystemNotificationMessageIdPrefix, data.MessageId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, systemNotificationIdKey, systemNotificationMessageIdKey)
	return err
}

func (m *defaultSystemNotificationModel) FindOne(ctx context.Context, id int64) (*SystemNotification, error) {
	systemNotificationIdKey := fmt.Sprintf("%s%v", cacheSystemNotificationIdPrefix, id)
	var resp SystemNotification
	err := m.QueryRowCtx(ctx, &resp, systemNotificationIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", systemNotificationRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSystemNotificationModel) FindOneByMessageId(ctx context.Context, messageId string) (*SystemNotification, error) {
	systemNotificationMessageIdKey := fmt.Sprintf("%s%v", cacheSystemNotificationMessageIdPrefix, messageId)
	var resp SystemNotification
	err := m.QueryRowIndexCtx(ctx, &resp, systemNotificationMessageIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `message_id` = ? limit 1", systemNotificationRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, messageId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSystemNotificationModel) Insert(ctx context.Context, data *SystemNotification) (sql.Result, error) {
	systemNotificationIdKey := fmt.Sprintf("%s%v", cacheSystemNotificationIdPrefix, data.Id)
	systemNotificationMessageIdKey := fmt.Sprintf("%s%v", cacheSystemNotificationMessageIdPrefix, data.MessageId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, systemNotificationRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.MessageId, data.ReceiverId, data.Type, data.Content, data.IsRead, data.CreatedTime, data.UpdatedTime)
	}, systemNotificationIdKey, systemNotificationMessageIdKey)
	return ret, err
}

func (m *defaultSystemNotificationModel) Update(ctx context.Context, newData *SystemNotification) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	systemNotificationIdKey := fmt.Sprintf("%s%v", cacheSystemNotificationIdPrefix, data.Id)
	systemNotificationMessageIdKey := fmt.Sprintf("%s%v", cacheSystemNotificationMessageIdPrefix, data.MessageId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, systemNotificationRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.MessageId, newData.ReceiverId, newData.Type, newData.Content, newData.IsRead, newData.CreatedTime, newData.UpdatedTime, newData.Id)
	}, systemNotificationIdKey, systemNotificationMessageIdKey)
	return err
}

func (m *defaultSystemNotificationModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSystemNotificationIdPrefix, primary)
}

func (m *defaultSystemNotificationModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", systemNotificationRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSystemNotificationModel) tableName() string {
	return m.table
}
