// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package red_packet

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	redPacketFieldNames          = builder.RawFieldNames(&RedPacket{})
	redPacketRows                = strings.Join(redPacketFieldNames, ",")
	redPacketRowsExpectAutoSet   = strings.Join(stringx.Remove(redPacketFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	redPacketRowsWithPlaceHolder = strings.Join(stringx.Remove(redPacketFieldNames, "`red_packet_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRedPacketRedPacketIdPrefix = "cache:redPacket:redPacketId:"
)

type (
	redPacketModel interface {
		Insert(ctx context.Context, data *RedPacket) (sql.Result, error)
		FindOne(ctx context.Context, redPacketId int64) (*RedPacket, error)
		Update(ctx context.Context, data *RedPacket) error
		Delete(ctx context.Context, redPacketId int64) error
	}

	defaultRedPacketModel struct {
		sqlc.CachedConn
		table string
	}

	RedPacket struct {
		RedPacketId          int64         `db:"red_packet_id"`           // 红包 ID
		SenderId             int64         `db:"sender_id"`               // 发送者用户 ID
		SessionId            int64         `db:"session_id"`              // 会话 ID（单聊或群聊）
		SessionType          sql.NullInt64 `db:"session_type"`            // 会话类型：0 群聊，1 单聊
		RedPacketWrapperText string        `db:"red_packet_wrapper_text"` // 红包封面文案
		RedPacketType        int64         `db:"red_packet_type"`         // 红包类型：0 普通红包，1 拼手气红包
		TotalAmount          int64         `db:"total_amount"`            // 红包总金额(单位：分)
		TotalCount           int64         `db:"total_count"`             // 红包总个数
		Status               int64         `db:"status"`                  // 状态：0 未领取完，1 已领取完，2 已过期
		CreatedTime          time.Time     `db:"created_time"`            // 创建时间
		UpdatedTime          time.Time     `db:"updated_time"`            // 更新时间
	}
)

func newRedPacketModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultRedPacketModel {
	return &defaultRedPacketModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`red_packet`",
	}
}

func (m *defaultRedPacketModel) Delete(ctx context.Context, redPacketId int64) error {
	redPacketRedPacketIdKey := fmt.Sprintf("%s%v", cacheRedPacketRedPacketIdPrefix, redPacketId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `red_packet_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, redPacketId)
	}, redPacketRedPacketIdKey)
	return err
}

func (m *defaultRedPacketModel) FindOne(ctx context.Context, redPacketId int64) (*RedPacket, error) {
	redPacketRedPacketIdKey := fmt.Sprintf("%s%v", cacheRedPacketRedPacketIdPrefix, redPacketId)
	var resp RedPacket
	err := m.QueryRowCtx(ctx, &resp, redPacketRedPacketIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `red_packet_id` = ? limit 1", redPacketRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, redPacketId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRedPacketModel) Insert(ctx context.Context, data *RedPacket) (sql.Result, error) {
	redPacketRedPacketIdKey := fmt.Sprintf("%s%v", cacheRedPacketRedPacketIdPrefix, data.RedPacketId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, redPacketRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.RedPacketId, data.SenderId, data.SessionId, data.SessionType, data.RedPacketWrapperText, data.RedPacketType, data.TotalAmount, data.TotalCount, data.Status, data.CreatedTime, data.UpdatedTime)
	}, redPacketRedPacketIdKey)
	return ret, err
}

func (m *defaultRedPacketModel) Update(ctx context.Context, data *RedPacket) error {
	redPacketRedPacketIdKey := fmt.Sprintf("%s%v", cacheRedPacketRedPacketIdPrefix, data.RedPacketId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `red_packet_id` = ?", m.table, redPacketRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.SenderId, data.SessionId, data.SessionType, data.RedPacketWrapperText, data.RedPacketType, data.TotalAmount, data.TotalCount, data.Status, data.CreatedTime, data.UpdatedTime, data.RedPacketId)
	}, redPacketRedPacketIdKey)
	return err
}

func (m *defaultRedPacketModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRedPacketRedPacketIdPrefix, primary)
}

func (m *defaultRedPacketModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `red_packet_id` = ? limit 1", redPacketRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultRedPacketModel) tableName() string {
	return m.table
}
