// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"
	"time"

	offlinedata "go-infinitechat/service/offline/api/internal/handler/offlinedata"
	systemnotification "go-infinitechat/service/offline/api/internal/handler/systemnotification"
	"go-infinitechat/service/offline/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/data",
				Handler: offlinedata.OfflineDataHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/historical/messages",
				Handler: offlinedata.HistoricalMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/messages",
				Handler: offlinedata.OfflineMessageHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/offline"),
		rest.WithTimeout(10000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/:userId/read/:notificationId",
				Handler: systemnotification.MarkAsReadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/:userId/read/all",
				Handler: systemnotification.MarkAllAsReadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/:userId/read/batch",
				Handler: systemnotification.MarkAsReadBatchHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:userId/unread",
				Handler: systemnotification.GetUnreadNotificationHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:userId/unread/count",
				Handler: systemnotification.GetUnreadCountHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/offline/notification"),
		rest.WithTimeout(10000*time.Millisecond),
	)
}
