// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package userrpc

import (
	"context"

	"go-infinitechat/service/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetUserInfosReq     = user.BatchGetUserInfosReq
	BatchGetUserInfosResp    = user.BatchGetUserInfosResp
	BatchUserInfoItem        = user.BatchUserInfoItem
	GroupMemberIdsResp       = user.GroupMemberIdsResp
	MessageValidateResp      = user.MessageValidateResp
	SessionIdReq             = user.SessionIdReq
	UserIdReq                = user.UserIdReq
	UserInfoResp             = user.UserInfoResp
	UserSessionRoleReq       = user.UserSessionRoleReq
	UserSessionRoleResp      = user.UserSessionRoleResp
	ValidateGroupMessageReq  = user.ValidateGroupMessageReq
	ValidateSingleMessageReq = user.ValidateSingleMessageReq

	UserRpc interface {
		GetGroupMemberIds(ctx context.Context, in *SessionIdReq, opts ...grpc.CallOption) (*GroupMemberIdsResp, error)
		GetUserInfo(ctx context.Context, in *UserIdReq, opts ...grpc.CallOption) (*UserInfoResp, error)
		BatchGetUserInfos(ctx context.Context, in *BatchGetUserInfosReq, opts ...grpc.CallOption) (*BatchGetUserInfosResp, error)
		GetUserSessionRole(ctx context.Context, in *UserSessionRoleReq, opts ...grpc.CallOption) (*UserSessionRoleResp, error)
		ValidateSingleMessage(ctx context.Context, in *ValidateSingleMessageReq, opts ...grpc.CallOption) (*MessageValidateResp, error)
		ValidateGroupMessage(ctx context.Context, in *ValidateGroupMessageReq, opts ...grpc.CallOption) (*MessageValidateResp, error)
	}

	defaultUserRpc struct {
		cli zrpc.Client
	}
)

func NewUserRpc(cli zrpc.Client) UserRpc {
	return &defaultUserRpc{
		cli: cli,
	}
}

func (m *defaultUserRpc) GetGroupMemberIds(ctx context.Context, in *SessionIdReq, opts ...grpc.CallOption) (*GroupMemberIdsResp, error) {
	client := user.NewUserRpcClient(m.cli.Conn())
	return client.GetGroupMemberIds(ctx, in, opts...)
}

func (m *defaultUserRpc) GetUserInfo(ctx context.Context, in *UserIdReq, opts ...grpc.CallOption) (*UserInfoResp, error) {
	client := user.NewUserRpcClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

func (m *defaultUserRpc) BatchGetUserInfos(ctx context.Context, in *BatchGetUserInfosReq, opts ...grpc.CallOption) (*BatchGetUserInfosResp, error) {
	client := user.NewUserRpcClient(m.cli.Conn())
	return client.BatchGetUserInfos(ctx, in, opts...)
}

func (m *defaultUserRpc) GetUserSessionRole(ctx context.Context, in *UserSessionRoleReq, opts ...grpc.CallOption) (*UserSessionRoleResp, error) {
	client := user.NewUserRpcClient(m.cli.Conn())
	return client.GetUserSessionRole(ctx, in, opts...)
}

func (m *defaultUserRpc) ValidateSingleMessage(ctx context.Context, in *ValidateSingleMessageReq, opts ...grpc.CallOption) (*MessageValidateResp, error) {
	client := user.NewUserRpcClient(m.cli.Conn())
	return client.ValidateSingleMessage(ctx, in, opts...)
}

func (m *defaultUserRpc) ValidateGroupMessage(ctx context.Context, in *ValidateGroupMessageReq, opts ...grpc.CallOption) (*MessageValidateResp, error) {
	client := user.NewUserRpcClient(m.cli.Conn())
	return client.ValidateGroupMessage(ctx, in, opts...)
}
