// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"go-infinitechat/service/user/rpc/internal/logic"
	"go-infinitechat/service/user/rpc/internal/svc"
	"go-infinitechat/service/user/rpc/user"
)

type UserRpcServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserRpcServer
}

func NewUserRpcServer(svcCtx *svc.ServiceContext) *UserRpcServer {
	return &UserRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *UserRpcServer) GetGroupMemberIds(ctx context.Context, in *user.SessionIdReq) (*user.GroupMemberIdsResp, error) {
	l := logic.NewGetGroupMemberIdsLogic(ctx, s.svcCtx)
	return l.GetGroupMemberIds(in)
}

func (s *UserRpcServer) GetUserInfo(ctx context.Context, in *user.UserIdReq) (*user.UserInfoResp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UserRpcServer) BatchGetUserInfos(ctx context.Context, in *user.BatchGetUserInfosReq) (*user.BatchGetUserInfosResp, error) {
	l := logic.NewBatchGetUserInfosLogic(ctx, s.svcCtx)
	return l.BatchGetUserInfos(in)
}

func (s *UserRpcServer) GetUserSessionRole(ctx context.Context, in *user.UserSessionRoleReq) (*user.UserSessionRoleResp, error) {
	l := logic.NewGetUserSessionRoleLogic(ctx, s.svcCtx)
	return l.GetUserSessionRole(in)
}

func (s *UserRpcServer) ValidateSingleMessage(ctx context.Context, in *user.ValidateSingleMessageReq) (*user.MessageValidateResp, error) {
	l := logic.NewValidateSingleMessageLogic(ctx, s.svcCtx)
	return l.ValidateSingleMessage(in)
}

func (s *UserRpcServer) ValidateGroupMessage(ctx context.Context, in *user.ValidateGroupMessageReq) (*user.MessageValidateResp, error) {
	l := logic.NewValidateGroupMessageLogic(ctx, s.svcCtx)
	return l.ValidateGroupMessage(in)
}
