// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"
	"time"

	"go-infinitechat/service/redpacket/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: GetRedPacketDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/basic",
				Handler: GetRedPacketBasicInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/receive",
				Handler: ReceiveRedPacketHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/send",
				Handler: SendRedPacketHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/chat/redPacket"),
		rest.WithTimeout(10000*time.Millisecond),
	)
}
