// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserRpc_GetGroupMemberIds_FullMethodName     = "/user.UserRpc/GetGroupMemberIds"
	UserRpc_GetUserInfo_FullMethodName           = "/user.UserRpc/GetUserInfo"
	UserRpc_BatchGetUserInfos_FullMethodName     = "/user.UserRpc/BatchGetUserInfos"
	UserRpc_GetUserSessionRole_FullMethodName    = "/user.UserRpc/GetUserSessionRole"
	UserRpc_ValidateSingleMessage_FullMethodName = "/user.UserRpc/ValidateSingleMessage"
	UserRpc_ValidateGroupMessage_FullMethodName  = "/user.UserRpc/ValidateGroupMessage"
)

// UserRpcClient is the client API for UserRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// rpc 服务
type UserRpcClient interface {
	GetGroupMemberIds(ctx context.Context, in *SessionIdReq, opts ...grpc.CallOption) (*GroupMemberIdsResp, error)
	GetUserInfo(ctx context.Context, in *UserIdReq, opts ...grpc.CallOption) (*UserInfoResp, error)
	BatchGetUserInfos(ctx context.Context, in *BatchGetUserInfosReq, opts ...grpc.CallOption) (*BatchGetUserInfosResp, error)
	GetUserSessionRole(ctx context.Context, in *UserSessionRoleReq, opts ...grpc.CallOption) (*UserSessionRoleResp, error)
	ValidateSingleMessage(ctx context.Context, in *ValidateSingleMessageReq, opts ...grpc.CallOption) (*MessageValidateResp, error)
	ValidateGroupMessage(ctx context.Context, in *ValidateGroupMessageReq, opts ...grpc.CallOption) (*MessageValidateResp, error)
}

type userRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewUserRpcClient(cc grpc.ClientConnInterface) UserRpcClient {
	return &userRpcClient{cc}
}

func (c *userRpcClient) GetGroupMemberIds(ctx context.Context, in *SessionIdReq, opts ...grpc.CallOption) (*GroupMemberIdsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupMemberIdsResp)
	err := c.cc.Invoke(ctx, UserRpc_GetGroupMemberIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) GetUserInfo(ctx context.Context, in *UserIdReq, opts ...grpc.CallOption) (*UserInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserInfoResp)
	err := c.cc.Invoke(ctx, UserRpc_GetUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) BatchGetUserInfos(ctx context.Context, in *BatchGetUserInfosReq, opts ...grpc.CallOption) (*BatchGetUserInfosResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetUserInfosResp)
	err := c.cc.Invoke(ctx, UserRpc_BatchGetUserInfos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) GetUserSessionRole(ctx context.Context, in *UserSessionRoleReq, opts ...grpc.CallOption) (*UserSessionRoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserSessionRoleResp)
	err := c.cc.Invoke(ctx, UserRpc_GetUserSessionRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) ValidateSingleMessage(ctx context.Context, in *ValidateSingleMessageReq, opts ...grpc.CallOption) (*MessageValidateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageValidateResp)
	err := c.cc.Invoke(ctx, UserRpc_ValidateSingleMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRpcClient) ValidateGroupMessage(ctx context.Context, in *ValidateGroupMessageReq, opts ...grpc.CallOption) (*MessageValidateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageValidateResp)
	err := c.cc.Invoke(ctx, UserRpc_ValidateGroupMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserRpcServer is the server API for UserRpc service.
// All implementations must embed UnimplementedUserRpcServer
// for forward compatibility.
//
// rpc 服务
type UserRpcServer interface {
	GetGroupMemberIds(context.Context, *SessionIdReq) (*GroupMemberIdsResp, error)
	GetUserInfo(context.Context, *UserIdReq) (*UserInfoResp, error)
	BatchGetUserInfos(context.Context, *BatchGetUserInfosReq) (*BatchGetUserInfosResp, error)
	GetUserSessionRole(context.Context, *UserSessionRoleReq) (*UserSessionRoleResp, error)
	ValidateSingleMessage(context.Context, *ValidateSingleMessageReq) (*MessageValidateResp, error)
	ValidateGroupMessage(context.Context, *ValidateGroupMessageReq) (*MessageValidateResp, error)
	mustEmbedUnimplementedUserRpcServer()
}

// UnimplementedUserRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserRpcServer struct{}

func (UnimplementedUserRpcServer) GetGroupMemberIds(context.Context, *SessionIdReq) (*GroupMemberIdsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupMemberIds not implemented")
}
func (UnimplementedUserRpcServer) GetUserInfo(context.Context, *UserIdReq) (*UserInfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedUserRpcServer) BatchGetUserInfos(context.Context, *BatchGetUserInfosReq) (*BatchGetUserInfosResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetUserInfos not implemented")
}
func (UnimplementedUserRpcServer) GetUserSessionRole(context.Context, *UserSessionRoleReq) (*UserSessionRoleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserSessionRole not implemented")
}
func (UnimplementedUserRpcServer) ValidateSingleMessage(context.Context, *ValidateSingleMessageReq) (*MessageValidateResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateSingleMessage not implemented")
}
func (UnimplementedUserRpcServer) ValidateGroupMessage(context.Context, *ValidateGroupMessageReq) (*MessageValidateResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateGroupMessage not implemented")
}
func (UnimplementedUserRpcServer) mustEmbedUnimplementedUserRpcServer() {}
func (UnimplementedUserRpcServer) testEmbeddedByValue()                 {}

// UnsafeUserRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserRpcServer will
// result in compilation errors.
type UnsafeUserRpcServer interface {
	mustEmbedUnimplementedUserRpcServer()
}

func RegisterUserRpcServer(s grpc.ServiceRegistrar, srv UserRpcServer) {
	// If the following call panics, it indicates UnimplementedUserRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserRpc_ServiceDesc, srv)
}

func _UserRpc_GetGroupMemberIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).GetGroupMemberIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_GetGroupMemberIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).GetGroupMemberIds(ctx, req.(*SessionIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).GetUserInfo(ctx, req.(*UserIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_BatchGetUserInfos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetUserInfosReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).BatchGetUserInfos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_BatchGetUserInfos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).BatchGetUserInfos(ctx, req.(*BatchGetUserInfosReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_GetUserSessionRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSessionRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).GetUserSessionRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_GetUserSessionRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).GetUserSessionRole(ctx, req.(*UserSessionRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_ValidateSingleMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateSingleMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).ValidateSingleMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_ValidateSingleMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).ValidateSingleMessage(ctx, req.(*ValidateSingleMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRpc_ValidateGroupMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateGroupMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServer).ValidateGroupMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpc_ValidateGroupMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServer).ValidateGroupMessage(ctx, req.(*ValidateGroupMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserRpc_ServiceDesc is the grpc.ServiceDesc for UserRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserRpc",
	HandlerType: (*UserRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGroupMemberIds",
			Handler:    _UserRpc_GetGroupMemberIds_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _UserRpc_GetUserInfo_Handler,
		},
		{
			MethodName: "BatchGetUserInfos",
			Handler:    _UserRpc_BatchGetUserInfos_Handler,
		},
		{
			MethodName: "GetUserSessionRole",
			Handler:    _UserRpc_GetUserSessionRole_Handler,
		},
		{
			MethodName: "ValidateSingleMessage",
			Handler:    _UserRpc_ValidateSingleMessage_Handler,
		},
		{
			MethodName: "ValidateGroupMessage",
			Handler:    _UserRpc_ValidateGroupMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
