// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求 / 响应
type SessionIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionIdReq) Reset() {
	*x = SessionIdReq{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionIdReq) ProtoMessage() {}

func (x *SessionIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionIdReq.ProtoReflect.Descriptor instead.
func (*SessionIdReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *SessionIdReq) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type GroupMemberIdsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMemberIdsResp) Reset() {
	*x = GroupMemberIdsResp{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberIdsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberIdsResp) ProtoMessage() {}

func (x *GroupMemberIdsResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberIdsResp.ProtoReflect.Descriptor instead.
func (*GroupMemberIdsResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *GroupMemberIdsResp) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type UserIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdReq) Reset() {
	*x = UserIdReq{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdReq) ProtoMessage() {}

func (x *UserIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdReq.ProtoReflect.Descriptor instead.
func (*UserIdReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserIdReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoResp) Reset() {
	*x = UserInfoResp{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoResp) ProtoMessage() {}

func (x *UserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoResp.ProtoReflect.Descriptor instead.
func (*UserInfoResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserInfoResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserInfoResp) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfoResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

// 批量获取用户信息
type BatchGetUserInfosReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUserInfosReq) Reset() {
	*x = BatchGetUserInfosReq{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUserInfosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUserInfosReq) ProtoMessage() {}

func (x *BatchGetUserInfosReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUserInfosReq.ProtoReflect.Descriptor instead.
func (*BatchGetUserInfosReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *BatchGetUserInfosReq) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type BatchUserInfoItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUserInfoItem) Reset() {
	*x = BatchUserInfoItem{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUserInfoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUserInfoItem) ProtoMessage() {}

func (x *BatchUserInfoItem) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUserInfoItem.ProtoReflect.Descriptor instead.
func (*BatchUserInfoItem) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *BatchUserInfoItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BatchUserInfoItem) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *BatchUserInfoItem) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type BatchGetUserInfosResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*BatchUserInfoItem   `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUserInfosResp) Reset() {
	*x = BatchGetUserInfosResp{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUserInfosResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUserInfosResp) ProtoMessage() {}

func (x *BatchGetUserInfosResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUserInfosResp.ProtoReflect.Descriptor instead.
func (*BatchGetUserInfosResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *BatchGetUserInfosResp) GetUsers() []*BatchUserInfoItem {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserSessionRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int64                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSessionRoleReq) Reset() {
	*x = UserSessionRoleReq{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSessionRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSessionRoleReq) ProtoMessage() {}

func (x *UserSessionRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSessionRoleReq.ProtoReflect.Descriptor instead.
func (*UserSessionRoleReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserSessionRoleReq) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *UserSessionRoleReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserSessionRoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          int32                  `protobuf:"varint,1,opt,name=Role,proto3" json:"Role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSessionRoleResp) Reset() {
	*x = UserSessionRoleResp{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSessionRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSessionRoleResp) ProtoMessage() {}

func (x *UserSessionRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSessionRoleResp.ProtoReflect.Descriptor instead.
func (*UserSessionRoleResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserSessionRoleResp) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type ValidateSingleMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int64                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId    int64                  `protobuf:"varint,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	SessionId     int64                  `protobuf:"varint,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSingleMessageReq) Reset() {
	*x = ValidateSingleMessageReq{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSingleMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSingleMessageReq) ProtoMessage() {}

func (x *ValidateSingleMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSingleMessageReq.ProtoReflect.Descriptor instead.
func (*ValidateSingleMessageReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateSingleMessageReq) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *ValidateSingleMessageReq) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *ValidateSingleMessageReq) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type ValidateGroupMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int64                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SessionId     int64                  `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateGroupMessageReq) Reset() {
	*x = ValidateGroupMessageReq{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateGroupMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateGroupMessageReq) ProtoMessage() {}

func (x *ValidateGroupMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateGroupMessageReq.ProtoReflect.Descriptor instead.
func (*ValidateGroupMessageReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *ValidateGroupMessageReq) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *ValidateGroupMessageReq) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type MessageValidateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	RejectReason  string                 `protobuf:"bytes,2,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	ErrorCode     int32                  `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageValidateResp) Reset() {
	*x = MessageValidateResp{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageValidateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageValidateResp) ProtoMessage() {}

func (x *MessageValidateResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageValidateResp.ProtoReflect.Descriptor instead.
func (*MessageValidateResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *MessageValidateResp) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *MessageValidateResp) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *MessageValidateResp) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\"-\n" +
	"\fSessionIdReq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\"/\n" +
	"\x12GroupMemberIdsResp\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\"$\n" +
	"\tUserIdReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"[\n" +
	"\fUserInfoResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"1\n" +
	"\x14BatchGetUserInfosReq\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\"`\n" +
	"\x11BatchUserInfoItem\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"F\n" +
	"\x15BatchGetUserInfosResp\x12-\n" +
	"\x05users\x18\x01 \x03(\v2\x17.user.BatchUserInfoItemR\x05users\"L\n" +
	"\x12UserSessionRoleReq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\")\n" +
	"\x13UserSessionRoleResp\x12\x12\n" +
	"\x04Role\x18\x01 \x01(\x05R\x04Role\"w\n" +
	"\x18ValidateSingleMessageReq\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x03R\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\x03R\n" +
	"receiverId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\x03R\tsessionId\"U\n" +
	"\x17ValidateGroupMessageReq\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x03R\bsenderId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\x03R\tsessionId\"s\n" +
	"\x13MessageValidateResp\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12#\n" +
	"\rreject_reason\x18\x02 \x01(\tR\frejectReason\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x05R\terrorCode2\xbf\x03\n" +
	"\aUserRpc\x12A\n" +
	"\x11GetGroupMemberIds\x12\x12.user.SessionIdReq\x1a\x18.user.GroupMemberIdsResp\x122\n" +
	"\vGetUserInfo\x12\x0f.user.UserIdReq\x1a\x12.user.UserInfoResp\x12L\n" +
	"\x11BatchGetUserInfos\x12\x1a.user.BatchGetUserInfosReq\x1a\x1b.user.BatchGetUserInfosResp\x12I\n" +
	"\x12GetUserSessionRole\x12\x18.user.UserSessionRoleReq\x1a\x19.user.UserSessionRoleResp\x12R\n" +
	"\x15ValidateSingleMessage\x12\x1e.user.ValidateSingleMessageReq\x1a\x19.user.MessageValidateResp\x12P\n" +
	"\x14ValidateGroupMessage\x12\x1d.user.ValidateGroupMessageReq\x1a\x19.user.MessageValidateRespB\bZ\x06./userb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_user_proto_goTypes = []any{
	(*SessionIdReq)(nil),             // 0: user.SessionIdReq
	(*GroupMemberIdsResp)(nil),       // 1: user.GroupMemberIdsResp
	(*UserIdReq)(nil),                // 2: user.UserIdReq
	(*UserInfoResp)(nil),             // 3: user.UserInfoResp
	(*BatchGetUserInfosReq)(nil),     // 4: user.BatchGetUserInfosReq
	(*BatchUserInfoItem)(nil),        // 5: user.BatchUserInfoItem
	(*BatchGetUserInfosResp)(nil),    // 6: user.BatchGetUserInfosResp
	(*UserSessionRoleReq)(nil),       // 7: user.UserSessionRoleReq
	(*UserSessionRoleResp)(nil),      // 8: user.UserSessionRoleResp
	(*ValidateSingleMessageReq)(nil), // 9: user.ValidateSingleMessageReq
	(*ValidateGroupMessageReq)(nil),  // 10: user.ValidateGroupMessageReq
	(*MessageValidateResp)(nil),      // 11: user.MessageValidateResp
}
var file_user_proto_depIdxs = []int32{
	5,  // 0: user.BatchGetUserInfosResp.users:type_name -> user.BatchUserInfoItem
	0,  // 1: user.UserRpc.GetGroupMemberIds:input_type -> user.SessionIdReq
	2,  // 2: user.UserRpc.GetUserInfo:input_type -> user.UserIdReq
	4,  // 3: user.UserRpc.BatchGetUserInfos:input_type -> user.BatchGetUserInfosReq
	7,  // 4: user.UserRpc.GetUserSessionRole:input_type -> user.UserSessionRoleReq
	9,  // 5: user.UserRpc.ValidateSingleMessage:input_type -> user.ValidateSingleMessageReq
	10, // 6: user.UserRpc.ValidateGroupMessage:input_type -> user.ValidateGroupMessageReq
	1,  // 7: user.UserRpc.GetGroupMemberIds:output_type -> user.GroupMemberIdsResp
	3,  // 8: user.UserRpc.GetUserInfo:output_type -> user.UserInfoResp
	6,  // 9: user.UserRpc.BatchGetUserInfos:output_type -> user.BatchGetUserInfosResp
	8,  // 10: user.UserRpc.GetUserSessionRole:output_type -> user.UserSessionRoleResp
	11, // 11: user.UserRpc.ValidateSingleMessage:output_type -> user.MessageValidateResp
	11, // 12: user.UserRpc.ValidateGroupMessage:output_type -> user.MessageValidateResp
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
