// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package balance_log

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	balanceLogFieldNames          = builder.RawFieldNames(&BalanceLog{})
	balanceLogRows                = strings.Join(balanceLogFieldNames, ",")
	balanceLogRowsExpectAutoSet   = strings.Join(stringx.Remove(balanceLogFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	balanceLogRowsWithPlaceHolder = strings.Join(stringx.Remove(balanceLogFieldNames, "`balance_log_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheBalanceLogBalanceLogIdPrefix = "cache:balanceLog:balanceLogId:"
)

type (
	balanceLogModel interface {
		Insert(ctx context.Context, data *BalanceLog) (sql.Result, error)
		FindOne(ctx context.Context, balanceLogId int64) (*BalanceLog, error)
		Update(ctx context.Context, data *BalanceLog) error
		Delete(ctx context.Context, balanceLogId int64) error
	}

	defaultBalanceLogModel struct {
		sqlc.CachedConn
		table string
	}

	BalanceLog struct {
		BalanceLogId int64         `db:"balance_log_id"` // 记录 ID
		UserId       int64         `db:"user_id"`        // 用户 ID
		Amount       int64         `db:"amount"`         // 变动金额（单位：分），正数为增加，负数为减少
		Type         int64         `db:"type"`           // 变动类型：0 发送红包，1 领取红包，2 红包退回
		RelatedId    sql.NullInt64 `db:"related_id"`     // 关联 ID，如红包 ID
		CreatedTime  time.Time     `db:"created_time"`   // 创建时间
		UpdatedTime  time.Time     `db:"updated_time"`   // 更新时间
	}
)

func newBalanceLogModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultBalanceLogModel {
	return &defaultBalanceLogModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`balance_log`",
	}
}

func (m *defaultBalanceLogModel) Delete(ctx context.Context, balanceLogId int64) error {
	balanceLogBalanceLogIdKey := fmt.Sprintf("%s%v", cacheBalanceLogBalanceLogIdPrefix, balanceLogId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `balance_log_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, balanceLogId)
	}, balanceLogBalanceLogIdKey)
	return err
}

func (m *defaultBalanceLogModel) FindOne(ctx context.Context, balanceLogId int64) (*BalanceLog, error) {
	balanceLogBalanceLogIdKey := fmt.Sprintf("%s%v", cacheBalanceLogBalanceLogIdPrefix, balanceLogId)
	var resp BalanceLog
	err := m.QueryRowCtx(ctx, &resp, balanceLogBalanceLogIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `balance_log_id` = ? limit 1", balanceLogRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, balanceLogId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBalanceLogModel) Insert(ctx context.Context, data *BalanceLog) (sql.Result, error) {
	balanceLogBalanceLogIdKey := fmt.Sprintf("%s%v", cacheBalanceLogBalanceLogIdPrefix, data.BalanceLogId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, balanceLogRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.BalanceLogId, data.UserId, data.Amount, data.Type, data.RelatedId, data.CreatedTime, data.UpdatedTime)
	}, balanceLogBalanceLogIdKey)
	return ret, err
}

func (m *defaultBalanceLogModel) Update(ctx context.Context, data *BalanceLog) error {
	balanceLogBalanceLogIdKey := fmt.Sprintf("%s%v", cacheBalanceLogBalanceLogIdPrefix, data.BalanceLogId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `balance_log_id` = ?", m.table, balanceLogRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.Amount, data.Type, data.RelatedId, data.CreatedTime, data.UpdatedTime, data.BalanceLogId)
	}, balanceLogBalanceLogIdKey)
	return err
}

func (m *defaultBalanceLogModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheBalanceLogBalanceLogIdPrefix, primary)
}

func (m *defaultBalanceLogModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `balance_log_id` = ? limit 1", balanceLogRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultBalanceLogModel) tableName() string {
	return m.table
}
