// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package red_packet_receive

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	redPacketReceiveFieldNames          = builder.RawFieldNames(&RedPacketReceive{})
	redPacketReceiveRows                = strings.Join(redPacketReceiveFieldNames, ",")
	redPacketReceiveRowsExpectAutoSet   = strings.Join(stringx.Remove(redPacketReceiveFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	redPacketReceiveRowsWithPlaceHolder = strings.Join(stringx.Remove(redPacketReceiveFieldNames, "`red_packet_receive_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheRedPacketReceiveRedPacketReceiveIdPrefix    = "cache:redPacketReceive:redPacketReceiveId:"
	cacheRedPacketReceiveRedPacketIdReceiverIdPrefix = "cache:redPacketReceive:redPacketId:receiverId:"
)

type (
	redPacketReceiveModel interface {
		Insert(ctx context.Context, data *RedPacketReceive) (sql.Result, error)
		FindOne(ctx context.Context, redPacketReceiveId int64) (*RedPacketReceive, error)
		FindOneByRedPacketIdReceiverId(ctx context.Context, redPacketId int64, receiverId int64) (*RedPacketReceive, error)
		Update(ctx context.Context, data *RedPacketReceive) error
		Delete(ctx context.Context, redPacketReceiveId int64) error
	}

	defaultRedPacketReceiveModel struct {
		sqlc.CachedConn
		table string
	}

	RedPacketReceive struct {
		RedPacketReceiveId int64     `db:"red_packet_receive_id"` // 记录 ID
		RedPacketId        int64     `db:"red_packet_id"`         // 红包 ID
		ReceiverId         int64     `db:"receiver_id"`           // 领取者用户 ID
		Amount             int64     `db:"amount"`                // 领取金额（单位：分）
		ReceivedAt         time.Time `db:"received_at"`           // 领取时间
		CreatedTime        time.Time `db:"created_time"`          // 创建时间
		UpdatedTime        time.Time `db:"updated_time"`          // 更新时间
	}
)

func newRedPacketReceiveModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultRedPacketReceiveModel {
	return &defaultRedPacketReceiveModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`red_packet_receive`",
	}
}

func (m *defaultRedPacketReceiveModel) Delete(ctx context.Context, redPacketReceiveId int64) error {
	data, err := m.FindOne(ctx, redPacketReceiveId)
	if err != nil {
		return err
	}

	redPacketReceiveRedPacketIdReceiverIdKey := fmt.Sprintf("%s%v:%v", cacheRedPacketReceiveRedPacketIdReceiverIdPrefix, data.RedPacketId, data.ReceiverId)
	redPacketReceiveRedPacketReceiveIdKey := fmt.Sprintf("%s%v", cacheRedPacketReceiveRedPacketReceiveIdPrefix, redPacketReceiveId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `red_packet_receive_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, redPacketReceiveId)
	}, redPacketReceiveRedPacketIdReceiverIdKey, redPacketReceiveRedPacketReceiveIdKey)
	return err
}

func (m *defaultRedPacketReceiveModel) FindOne(ctx context.Context, redPacketReceiveId int64) (*RedPacketReceive, error) {
	redPacketReceiveRedPacketReceiveIdKey := fmt.Sprintf("%s%v", cacheRedPacketReceiveRedPacketReceiveIdPrefix, redPacketReceiveId)
	var resp RedPacketReceive
	err := m.QueryRowCtx(ctx, &resp, redPacketReceiveRedPacketReceiveIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `red_packet_receive_id` = ? limit 1", redPacketReceiveRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, redPacketReceiveId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRedPacketReceiveModel) FindOneByRedPacketIdReceiverId(ctx context.Context, redPacketId int64, receiverId int64) (*RedPacketReceive, error) {
	redPacketReceiveRedPacketIdReceiverIdKey := fmt.Sprintf("%s%v:%v", cacheRedPacketReceiveRedPacketIdReceiverIdPrefix, redPacketId, receiverId)
	var resp RedPacketReceive
	err := m.QueryRowIndexCtx(ctx, &resp, redPacketReceiveRedPacketIdReceiverIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `red_packet_id` = ? and `receiver_id` = ? limit 1", redPacketReceiveRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, redPacketId, receiverId); err != nil {
			return nil, err
		}
		return resp.RedPacketReceiveId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRedPacketReceiveModel) Insert(ctx context.Context, data *RedPacketReceive) (sql.Result, error) {
	redPacketReceiveRedPacketIdReceiverIdKey := fmt.Sprintf("%s%v:%v", cacheRedPacketReceiveRedPacketIdReceiverIdPrefix, data.RedPacketId, data.ReceiverId)
	redPacketReceiveRedPacketReceiveIdKey := fmt.Sprintf("%s%v", cacheRedPacketReceiveRedPacketReceiveIdPrefix, data.RedPacketReceiveId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, redPacketReceiveRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.RedPacketReceiveId, data.RedPacketId, data.ReceiverId, data.Amount, data.ReceivedAt, data.CreatedTime, data.UpdatedTime)
	}, redPacketReceiveRedPacketIdReceiverIdKey, redPacketReceiveRedPacketReceiveIdKey)
	return ret, err
}

func (m *defaultRedPacketReceiveModel) Update(ctx context.Context, newData *RedPacketReceive) error {
	data, err := m.FindOne(ctx, newData.RedPacketReceiveId)
	if err != nil {
		return err
	}

	redPacketReceiveRedPacketIdReceiverIdKey := fmt.Sprintf("%s%v:%v", cacheRedPacketReceiveRedPacketIdReceiverIdPrefix, data.RedPacketId, data.ReceiverId)
	redPacketReceiveRedPacketReceiveIdKey := fmt.Sprintf("%s%v", cacheRedPacketReceiveRedPacketReceiveIdPrefix, data.RedPacketReceiveId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `red_packet_receive_id` = ?", m.table, redPacketReceiveRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.RedPacketId, newData.ReceiverId, newData.Amount, newData.ReceivedAt, newData.CreatedTime, newData.UpdatedTime, newData.RedPacketReceiveId)
	}, redPacketReceiveRedPacketIdReceiverIdKey, redPacketReceiveRedPacketReceiveIdKey)
	return err
}

func (m *defaultRedPacketReceiveModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheRedPacketReceiveRedPacketReceiveIdPrefix, primary)
}

func (m *defaultRedPacketReceiveModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `red_packet_receive_id` = ? limit 1", redPacketReceiveRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultRedPacketReceiveModel) tableName() string {
	return m.table
}
