// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"
	"time"

	user "go-infinitechat/service/user/api/internal/handler/user"
	"go-infinitechat/service/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/refresh",
				Handler: user.RefreshTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/avatar",
				Handler: user.UpdateAvatarHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/balance/:userId",
				Handler: user.GetUserBalanceHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/balance/detail/:userId",
				Handler: user.GetBalanceDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/captcha",
				Handler: user.CaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/loginCode",
				Handler: user.LoginCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/loginPassword",
				Handler: user.LoginPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/logout",
				Handler: user.LogoutHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/refreshUri",
				Handler: user.RefreshUriHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/updatePassword",
				Handler: user.UpdatePasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/uploadUrl",
				Handler: user.GetUploadUrlHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/info",
				Handler: user.UserInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user"),
		rest.WithTimeout(10000*time.Millisecond),
	)
}
