// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"
	"time"

	user "go-infinitechat/service/user/api/internal/handler/user"
	"go-infinitechat/service/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/refresh",
				Handler: user.RefreshTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/avatar",
				Handler: user.UpdateAvatarHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/captcha",
				Handler: user.CaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/logout",
				Handler: user.LogoutHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/password",
				Handler: user.UpdatePasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/refreshUri",
				Handler: user.RefreshUriHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/upload-url",
				Handler: user.GetUploadUrlHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users/:userId",
				Handler: user.UserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users/:userId/balance",
				Handler: user.GetUserBalanceHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users/:userId/balance/records",
				Handler: user.GetBalanceDetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user"),
		rest.WithTimeout(10000*time.Millisecond),
	)
}
