// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"
	"time"

	user "go-infinitechat/service/user/api/internal/handler/user"
	"go-infinitechat/service/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/loginPassword",
				Handler: user.LoginPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sendCaptcha",
				Handler: user.SendCaptchaHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user"),
		rest.WithTimeout(10000*time.Millisecond),
	)
}
