// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ReceiveResultVO struct {
	Status  int    `json:"status"`
	Message string `json:"message"`
	Amount  string `json:"amount,optional"` // 元
}

type RedPacketBasicRequest struct {
	RedPacketId int64 `form:"redPacketId"  validate:"required,gt=0" msg:"红包ID不能为空"`
}

type RedPacketBasicVO struct {
	RedPacketId    int64  `json:"redPacketId"`
	RedPacketType  int    `json:"redPacketType"`
	TotalAmount    string `json:"totalAmount"`
	TotalCount     int    `json:"totalCount"`
	ReceivedCount  int    `json:"receivedCount"`
	ReceivedAmount string `json:"receivedAmount"`
	Status         int    `json:"status"`
	CreatedTime    string `json:"createdTime"`
}

type RedPacketDetailRequest struct {
	RedPacketId int64 `form:"redPacketId" validate:"required,gt=0" msg:"红包ID不能为空"`
	PageNum     int   `form:"pageNum,default=1"`
	PageSize    int   `form:"pageSize,default=10"`
}

type RedPacketDetailVO struct {
	RedPacketId          int64                `json:"redPacketId"`
	SenderId             int64                `json:"senderId"`
	SenderNickname       string               `json:"senderNickname"`
	SenderAvatar         string               `json:"senderAvatar"`
	SessionId            int64                `json:"sessionId"`
	SessionType          int                  `json:"sessionType"`
	RedPacketWrapperText string               `json:"redPacketWrapperText"`
	RedPacketType        int                  `json:"redPacketType"`
	TotalAmount          string               `json:"totalAmount"`
	TotalCount           int                  `json:"totalCount"`     // 红包总个数
	ReceivedCount        int                  `json:"receivedCount"`  // 已领取的个数
	ReceivedAmount       string               `json:"receivedAmount"` // 已领取的总金额
	Status               int                  `json:"status"`
	CreatedTime          string               `json:"createdTime"`
	ReceiveRecords       []RedPacketReceiveVO `json:"receiveRecords"`
}

type RedPacketReceiveRequest struct {
	UserId      int64 `json:"userId" validate:"required,gt=0" msg:"用户ID不能为空"`
	RedPacketId int64 `json:"redPacketId" validate:"required,gt=0" msg:"红包ID不能为空"`
}

type RedPacketReceiveVO struct {
	ReceiverId       int64  `json:"receiverId"`
	ReceiverNickname string `json:"receiverNickname"`
	ReceiverAvatar   string `json:"receiverAvatar"`
	Amount           string `json:"amount"`     // 接收者的领取金额
	ReceivedAt       string `json:"receivedAt"` // 接收者的领取时间
}

type RedPacketSendRequest struct {
	SenderId        int64                    `json:"senderId" validate:"required,gt=0" msg:"发送者ID不能为空"`
	SessionId       int64                    `json:"sessionId" validate:"required,gt=0" msg:"会话ID不能为空"`
	SessionType     int32                    `json:"sessionType" validate:"oneof=0 1" msg:"会话类型错误"`
	ReceiverId      *int64                   `json:"receiverId,optional"`
	Type            int32                    `json:"type,optional"`
	ClientMessageId string                   `json:"clientMessageId,optional" `
	Body            RedPacketSendRequestBody `json:"body" validate:"required"`
}

type RedPacketSendRequestBody struct {
	RedPacketType        int32  `json:"redPacketType" validate:"oneof=0 1" msg:"红包类型错误"`
	TotalAmount          string `json:"totalAmount" validate:"required" msg:"红包金额不能为空"` // 元，字符串避免精度问题
	TotalCount           int32  `json:"totalCount" validate:"required,gt=0" msg:"红包数量必须大于0"`
	RedPacketWrapperText string `json:"redPacketWrapperText,optional"`
}

type RedPacketSendVO struct {
	RedPacketId int64 `json:"redPacketId"`
	MessageId   int64 `json:"messageId"`
}
