// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GetUnreadCountRequest struct {
	UserId int64 `path:"userId" validate:"required" msg:"用户ID不能为空"`
}

type GetUnreadNotificationsRequest struct {
	UserId   int64 `path:"userId" validate:"required" msg:"用户ID不能为空"`
	PageNum  int32 `form:"pageNum,default=1"`
	PageSize int32 `form:"pageSize,default=20,range=[1:100]"`
}

type HistoryMessageRequest struct {
	SessionId int64  `json:"sessionId"`
	Time      string `json:"time"`
}

type MarkAllAsReadRequest struct {
	UserId int64 `path:"userId" validate:"required" msg:"用户ID不能为空"`
}

type MarkAsReadBatchRequest struct {
	UserId          int64   `path:"userId" validate:"required" msg:"用户ID不能为空"`
	NotificationIds []int64 `json:"notificationIds" validate:"required" msg:"通知ID不能为空"`
}

type MarkAsReadRequest struct {
	UserId         int64 `path:"userId" validate:"required" msg:"用户ID不能为空"`
	NotificationId int64 `path:"notificationId" validate:"required" msg:"通知ID不能为空"`
}

type MessageBody struct {
	Content              string `json:"content"`
	ReplyId              int64  `json:"replyId"`
	RedPacketId          string `json:"redPacketId"`          //红包ID（红包消息专用）
	RedPacketWrapperText string `json:"redPacketWrapperText"` //  红包封面文案（红包消息专用）
}

type OfflineDataRequest struct {
	UserId int64 `form:"userId" validate:"required" msg:"用户ID不能为空"`
}

type OfflineDataResponse struct {
	Type           int32  `json:"type"`
	SessionType    int32  `json:"sessionType"`
	SessionId      int64  `json:"sessionId"`
	SenderId       int64  `json:"senderId"`
	Avatar         string `json:"avatar"`
	Name           string `json:"name"`
	LastMsgContent string `json:"lastMsgContent"`
	LastMsgTime    string `json:"lastMsgTime"`
	Count          int32  `json:"count"`
}

type OfflineHistoryMessageResponse struct {
	Type        int32       `json:"type"`
	SenderId    int64       `json:"senderId"`
	Avatar      string      `json:"avatar"`
	Name        string      `json:"name"`
	CreatedTime string      `json:"createdTime"`
	Body        MessageBody `json:"body"`
}

type OfflineMessageRequest struct {
	SessionId          int64 `json:"sessionId"`
	UnreadOfflineCount int32 `json:"unreadOfflineCount"`
}
