// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LoginRequest struct {
	Account  string `json:"account" form:"account,optional" validate:"required" msg:"required=账号不能为空"`
	Password string `json:"password" form:"password,optional" validate:"required" msg:"required=密码不能为空"`
}

type LoginResponse struct {
	UserId       int64  `json:"userId" `
	Nickname     string `json:"nickName,omitempty" `
	Avatar       string `json:"avatar,omitempty"`
	Gender       int64  `json:"gender"`
	Description  string `json:"description,omitempty"`
	State        int64  `json:"state"`
	Role         int64  `json:"role"`
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
	WeServiceUrl string `json:"weServiceUrl"`
}
